### ISSUE TITLE
ZarinPal/ShetabViewController.swift:142

### ISSUE THREAD

**Issue by NSMohammad** [ZarinPal/iOS-SDK#5]
after app enters foreground from payment safari page
error given
ZarinPal/ShetabViewController.swift:142: Fatal error: Unexpectedly found nil while unwrapping an Optional valu
<img width="1146" alt="Screen Shot 1401-01-08 at 19 07 26" src="https://user-images.githubusercontent.com/55185826/160423888-3256d938-6612-4f5b-8f03-1af5d9334e2b.png">
e

**Comment by FarshidRoohi** [comment]
Hi Mohammad

You can update ZarinPal SDK to the last version and fix this issue.

last version:  [1.1.14](https://github.com/ZarinPal/iOS-SDK/releases/tag/1.1.14)
install: [docs](https://github.com/ZarinPal/iOS-SDK/releases/tag/1.1.14)

**Comment by NSMohammad** [comment]
nope this issue not done.
if payment failed or cancel then open app anythings is ok,
but if payment success and come back to app again error ZarinPal/ShetabViewController.swift find nil.

i changed [1.1.14] version on pods file and use install repo update

**Comment by FarshidRoohi** [comment]
OK, I'm checking this problem.
Do you use MPG? or open a browser?

@NSMohammad

**Comment by NSMohammad** [comment]
idk whats MPG means,
'MPG' use payment in app?
now app open payment page to browser

**Comment by FarshidRoohi** [comment]
I found your problem and release a new version, you can use it:

https://github.com/ZarinPal/iOS-SDK/releases/tag/1.1.15

**Comment by NSMohammad** [comment]
Ty 👍
