### ISSUE TITLE
return to app in real device

### ISSUE THREAD

**Issue by NSMohammad** [ZarinPal/iOS-SDK#6]
hi
while payment success done and back to app, method `didException(exception: NSException)` called and write "**unknown error**" in real device.
in the simulator everythink is ok.

![WhatsApp Image 2022-04-24 at 6 24 05 PM](https://user-images.githubusercontent.com/55185826/165054906-58cefe5f-be2e-46bd-9aa4-75445d68f5d9.jpeg)

**Comment by FarshidRoohi** [comment]
Hi @NSMohammad, I'm Checking this problem and I notify you very soon

**Comment by FarshidRoohi** [comment]
You can update SDK and This problem is solved.

https://github.com/ZarinPal/iOS-SDK/releases/tag/1.1.16
