### ISSUE TITLE
some times crash v1.1.17beta

### ISSUE THREAD

**Issue by NSMohammad** [ZarinPal/iOS-SDK#7]
<img width="1440" alt="Screen Shot 1401-02-31 at 12 05 18" src="https://user-images.githubusercontent.com/55185826/169641374-3f94b4f6-75ce-437c-abe1-4facb44c8390.png">

**Comment by FarshidRoohi** [comment]
Hi @NSMohammad thanks for reporting this issue, you can share with me more information:
Xcode version: -
Simulator or real devices iOS version: -
ZarinPal framework version: -

**Comment by NSMohammad** [comment]
hi
xcode version 13.2.1 
real device ios 15.4.1
and framework version 1.1.17-beta

**Comment by FarshidRoohi** [comment]
iOS version?

**Comment by NSMohammad** [comment]
ios version: 15.4.1
@FarshidRoohi 
ty
